sonar.projectKey=agussantinelli_GitData
sonar.organization=agussantinelli

# Directorios a analizar (ignorando node_modules y tests)
sonar.sources=apps/web/src,apps/api/src
sonar.exclusions=**/tests/**,**/*.test.tsx,**/*.test.ts,**/node_modules/**,**/dist/**,**/build/**

# Dónde buscar la cobertura de código
sonar.javascript.lcov.reportPaths=apps/web/coverage/lcov.info,apps/api/coverage/lcov.info

# Indicar los tests para métricas (Opcional)
sonar.tests=apps/web/src,apps/api/src
sonar.test.inclusions=**/*.test.tsx,**/*.test.ts
